Parameters:
  KeyName:
    Description: Name of an exsting EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameters
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:
#VPC
  NATInstanceVPC1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.40.0.0/16
      Tags:
        - Key: Name
          Value: NATInstance-VPC1

#인터넷 게이트웨이
  NATInstanceIGW1:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: NATInstance-IGW1
  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref NATInstanceIGW1
      VpcId: !Ref NATInstanceVPC1
#서브넷
  NATInstanceVPC1Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.40.1.0/24
      VpcId: !Ref NATInstanceVPC1
      AvailabilityZone: !Select [ 0, !GetAZs '']
      Tags:
        - Key: Name
          Value: NATInstance-VPC1-Subnet1
  NATInstanceVPC1Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.40.2.0/24
      VpcId: !Ref NATInstanceVPC1
      AvailabilityZone: !Select [ 0, !GetAZs '']
      Tags:
        - Key: Name
          Value: NATInstance-VPC1-Subnet2s

#RT
  NATInstancePublicRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref NATInstanceVPC1
      Tags:
        - Key: Name
          Value: NATInstance-PublicRouteTable1 
  NATInstancePrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref NATInstanceVPC1
      Tags:
        - Key: Name
          Value: NATInstance-PrivateRouteTable1 


  NATRoute1:
    Type: AWS::EC2::Route
    DependsOn: IGWAttachment
    Properties:
      RouteTableId: !Ref NATInstancePrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NetworkInterfaceId: !Ref Instance1ENIEth0

  PublicRoute1:
    Type: AWS::EC2::Route
    DependsOn: IGWAttachment
    Properties:
      RouteTableId: !Ref NATInstancePublicRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref NATInstanceIGW1



# 서브넷 라우트 연결
  Public1SNRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref NATInstanceVPC1Subnet1
      RouteTableId: !Ref NATInstancePublicRouteTable1
  Private1SNRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref NATInstanceVPC1Subnet2
      RouteTableId: !Ref NATInstancePrivateRouteTable1

#보안그룹
  NATInstaceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable ssh http access
      VpcId: !Ref NATInstanceVPC1
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 10.40.0.0/16
  PrivateEC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ssh access
      VpcId: !Ref NATInstanceVPC1
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0

#인스턴스
  Private1EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c76973fbe0ee100c
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: Private-EC2-1
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref NATInstanceVPC1Subnet2
          GroupSet: 
          - !Ref PrivateEC2SG
          PrivateIpAddress: 10.40.2.101
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            (
            echo "qwe123"
            echo "qwe123"
            ) | passwd --stdin root
            sed -i "s/^PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
            sed -i "s/^#PermitRootLogin yes/PermitRootLogin yes/g" /etc/ssh/sshd_config
            service sshd restart
        
  Private2EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c76973fbe0ee100c
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: Private-EC2-2
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref NATInstanceVPC1Subnet2
          GroupSet: 
          - !Ref PrivateEC2SG
          PrivateIpAddress: 10.40.2.102
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            (
            echo "qwe123"
            echo "qwe123"
            ) | passwd --stdin root
            sed -i "s/^PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
            sed -i "s/^#PermitRootLogin yes/PermitRootLogin yes/g" /etc/ssh/sshd_config
            service sshd restart
  #NAT 인스턴스
  Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e3e1b45a02a17920
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SourceDestCheck: false
      Tags:
        - Key: Name
          Value: NAT-Instance
      NetworkInterfaces:
        - DeviceIndex: 0
          NetworkInterfaceId: !Ref Instance1ENIEth0
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            hostname NAT-Instance
            yum -y install tcpdump iptraf
 #인터페이스 랜카드 
  Instance1ENIEth0:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref NATInstanceVPC1Subnet1
      Description: Instance1 eh0
      GroupSet:
      - !Ref NATInstaceSG
      PrivateIpAddress: 10.40.1.100
      Tags:
        - Key: Name
          Value: NAT-Instance eth0

  VPCEIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  VPCAssociateEIP1:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt VPCEIP1.AllocationId
      NetworkInterfaceId: !Ref Instance1ENIEth0
      


        

      